"""
Convenient JSON definitions for use.
You can use this site to easily explore JSON paths: https://jsonpathfinder.com/
"""
defs = {
    "name":
    "gemini",
    "includes": [
        "$.['$ref']",
        "$.['$schema']",
        "$.definitions.Aggregate",
        "$.definitions.NonArgAggregateOp",
        "$.definitions.AnyMark",
        "$.definitions.ColorDef",
        "$.definitions.Data",
        "$.definitions.DataFormat",
        "$.definitions.DataSource",
        "$.definitions.FacetedEncoding",
        "$.definitions.Field",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>']",
        "$.definitions.PositionDef",
        "$.definitions.FieldName",
        "$.definitions.CsvDataFormat",
        "$.definitions.Mark",
        "$.definitions.['MarkPropDef<(Gradient|string|null)>']",
        "$.definitions.Parse",
        "$.definitions.ParseValue",
        "$.definitions.PolarDef",
        "$.definitions.PositionFieldDef",
        "$.definitions.PositionFieldDefBase",
        "$.definitions.Scale",
        "$.definitions.StandardType",
        "$.definitions.Text",
        "$.definitions.TopLevelSpec",
        "$.definitions.TopLevelUnitSpec",
        "$.definitions.UrlData",
    ],
    "excludes": [
        "$.definitions.Aggregate.anyOf[1]",
        "$.definitions.Aggregate.anyOf[2]",
        "$.definitions.AnyMark.anyOf[0]",
        "$.definitions.AnyMark.anyOf[1]",
        "$.definitions.AnyMark.anyOf[3]",
        "$.definitions.Data.anyOf[1]",
        "$.definitions.DataFormat.anyOf[1]",
        "$.definitions.DataFormat.anyOf[2]",
        "$.definitions.DataFormat.anyOf[3]",
        "$.definitions.DataSource.anyOf[1]",
        "$.definitions.DataSource.anyOf[2]",
        "$.definitions.DataSource.anyOf[3]",
        "$.definitions.FacetedEncoding.properties.angle",
        "$.definitions.FacetedEncoding.properties.column",
        "$.definitions.FacetedEncoding.properties.description",
        "$.definitions.FacetedEncoding.properties.detail",
        "$.definitions.FacetedEncoding.properties.facet",
        "$.definitions.FacetedEncoding.properties.fill",
        "$.definitions.FacetedEncoding.properties.fillOpacity",
        "$.definitions.FacetedEncoding.properties.href",
        "$.definitions.FacetedEncoding.properties.key",
        "$.definitions.FacetedEncoding.properties.latitude",
        "$.definitions.FacetedEncoding.properties.latitude2",
        "$.definitions.FacetedEncoding.properties.longitude",
        "$.definitions.FacetedEncoding.properties.longitude2",
        "$.definitions.FacetedEncoding.properties.opacity",
        "$.definitions.FacetedEncoding.properties.order",
        "$.definitions.FacetedEncoding.properties.opacity",
        "$.definitions.FacetedEncoding.properties.radius",
        "$.definitions.FacetedEncoding.properties.radius2",
        "$.definitions.FacetedEncoding.properties.row",
        "$.definitions.FacetedEncoding.properties.shape",
        "$.definitions.FacetedEncoding.properties.size",
        "$.definitions.FacetedEncoding.properties.stroke",
        "$.definitions.FacetedEncoding.properties.strokeDash",
        "$.definitions.FacetedEncoding.properties.strokeOpacity",
        "$.definitions.FacetedEncoding.properties.strokeWidth",
        "$.definitions.FacetedEncoding.properties.text",
        "$.definitions.FacetedEncoding.properties.theta2",
        "$.definitions.FacetedEncoding.properties.time",
        "$.definitions.FacetedEncoding.properties.tooltip",
        "$.definitions.FacetedEncoding.properties.url",
        "$.definitions.FacetedEncoding.properties.x2",
        "$.definitions.FacetedEncoding.properties.xError",
        "$.definitions.FacetedEncoding.properties.xError2",
        "$.definitions.FacetedEncoding.properties.xOffset",
        "$.definitions.FacetedEncoding.properties.y2",
        "$.definitions.FacetedEncoding.properties.yError",
        "$.definitions.FacetedEncoding.properties.yError2",
        "$.definitions.FacetedEncoding.properties.yOffset",
        "$.definitions.Field.anyOf[1]",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.aggregate",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.bandPosition",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.bin",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.condition",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.legend",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.scale.anyOf[1]",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.sort",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.timeUnit",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.title.anyOf[1]",
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].properties.type",
        "$.definitions.['MarkPropDef<(Gradient|string|null)>'].anyOf[1]",
        "$.definitions.['MarkPropDef<(Gradient|string|null)>'].anyOf[2]",
        "$.definitions.PolarDef.anyOf[1]",
        "$.definitions.PolarDef.anyOf[2]",
        "$.definitions.PositionDef.anyOf[1]",
        "$.definitions.PositionDef.anyOf[2]",
        "$.definitions.PositionFieldDef.properties.axis",
        "$.definitions.PositionFieldDef.properties.bandPosition",
        "$.definitions.PositionFieldDef.properties.bin.anyOf[1]",
        "$.definitions.PositionFieldDef.properties.bin.anyOf[2]",
        "$.definitions.PositionFieldDef.properties.bin.anyOf[3]",
        "$.definitions.PositionFieldDef.properties.impute",
        "$.definitions.PositionFieldDef.properties.scale",
        "$.definitions.PositionFieldDef.properties.sort",
        "$.definitions.PositionFieldDef.properties.stack",
        "$.definitions.PositionFieldDef.properties.timeUnit",
        "$.definitions.PositionFieldDef.properties.title.anyOf[1]",
        "$.definitions.PositionFieldDefBase.properties.aggregate",
        "$.definitions.PositionFieldDefBase.properties.bandPosition",
        "$.definitions.PositionFieldDefBase.properties.bin",
        "$.definitions.PositionFieldDefBase.properties.scale",
        "$.definitions.PositionFieldDefBase.properties.sort",
        "$.definitions.PositionFieldDefBase.properties.stack",
        "$.definitions.PositionFieldDefBase.properties.timeUnit",
        "$.definitions.PositionFieldDefBase.properties.title",
        "$.definitions.Scale.properties",
        "$.definitions.Text.anyOf[1]",
        "$.definitions.Text.anyOf[2]",
        "$.definitions.TopLevelSpec.anyOf[1]",
        "$.definitions.TopLevelSpec.anyOf[2]",
        "$.definitions.TopLevelSpec.anyOf[3]",
        "$.definitions.TopLevelSpec.anyOf[4]",
        "$.definitions.TopLevelSpec.anyOf[5]",
        "$.definitions.TopLevelSpec.anyOf[6]",
        "$.definitions.TopLevelUnitSpec.properties.['$schema']",
        "$.definitions.TopLevelUnitSpec.properties.align",
        "$.definitions.TopLevelUnitSpec.properties.autosize",
        "$.definitions.TopLevelUnitSpec.properties.background",
        "$.definitions.TopLevelUnitSpec.properties.bounds",
        "$.definitions.TopLevelUnitSpec.properties.center",
        "$.definitions.TopLevelUnitSpec.properties.config",
        "$.definitions.TopLevelUnitSpec.properties.data.anyOf[1]",
        "$.definitions.TopLevelUnitSpec.properties.datasets",
        "$.definitions.TopLevelUnitSpec.properties.description",
        "$.definitions.TopLevelUnitSpec.properties.height",
        "$.definitions.TopLevelUnitSpec.properties.name",
        "$.definitions.TopLevelUnitSpec.properties.padding",
        "$.definitions.TopLevelUnitSpec.properties.params",
        "$.definitions.TopLevelUnitSpec.properties.projection",
        "$.definitions.TopLevelUnitSpec.properties.resolve",
        "$.definitions.TopLevelUnitSpec.properties.spacing",
        "$.definitions.TopLevelUnitSpec.properties.title.anyOf[1]",
        "$.definitions.TopLevelUnitSpec.properties.transform",
        "$.definitions.TopLevelUnitSpec.properties.usermeta",
        "$.definitions.TopLevelUnitSpec.properties.view",
        "$.definitions.TopLevelUnitSpec.properties.width",
        "$.definitions.CsvDataFormat.properties.parse",
        "$.definitions.UrlData.properties.name",
    ],
    "unresolving_definitions": [],
    "replace": {
        "$.definitions.CsvDataFormat.required": ["type"],
        "$.definitions.CsvDataFormat.properties.type.description":
        "Type of input data. Only 'csv' is supported.",
        "$.definitions.CsvDataFormat.properties.type.enum": ["csv"],
        "$.definitions.Encoding.required": ["color", "x", "y"],
        "$.definitions.['FieldOrDatumDefWithCondition<MarkPropFieldDef,(Gradient|string|null)>'].required":
        ["field", "scale", "title"],
        "$.definitions.Mark.enum": ["bar", "arc", "circle", "line"],
        "$.definitions.NonArgAggregateOp.enum": ["count"],
        "$.definitions.PositionFieldDef.required": ["field", "title", "type"],
        "$.definitions.UrlData.required": ["url", "format"],
        "$.definitions.UrlData.properties.url.description":
        "CSV file path",
        "$.definitions.Scale.properties": {
            "scheme": {
                "description":
                "A string indicating a color [scheme](https://vega.github.io/vega-lite/docs/scale.html#scheme) name (e.g., `\"category10\"` or `\"blues\"`) or a [scheme parameter object](https://vega.github.io/vega-lite/docs/scale.html#scheme-params).\n\nDiscrete color schemes may be used with [discrete](https://vega.github.io/vega-lite/docs/scale.html#discrete) or [discretizing](https://vega.github.io/vega-lite/docs/scale.html#discretizing) scales. Continuous color schemes are intended for use with color scales.\n\nTo set a custom scheme, instead set the list of values [as the scale range](https://vega.github.io/vega-lite/docs/scale.html#2-setting-the-range-property-to-an-array-of-valid-css-color-strings).\n\nFor the full list of supported schemes, please refer to the [Vega Scheme](https://vega.github.io/vega/docs/schemes/#reference) reference.",
                "enum": ["category10"],
                "type": "string",
            },
        },
        "$.definitions.Scale.required": ["scheme"],
        "$.definitions.TopLevelUnitSpec.required":
        ["data", "encoding", "mark", "title"],
    },
    "remove_fields": ["additionalProperties", "$schema"]
}
